# Generated by Django 3.2.16 on 2022-11-17 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('population', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('diseaseTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('diseaseTypeDescription', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HospitalManagementApp.users')),
                ('degree', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PublicServant',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HospitalManagementApp.users')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pathogen', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=140)),
                ('diseaseTypeId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.diseasetype')),
            ],
        ),
        migrations.CreateModel(
            name='Specialize',
            fields=[
                ('diseaseTypeId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HospitalManagementApp.diseasetype')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Discover',
            fields=[
                ('cname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HospitalManagementApp.country')),
                ('first_enc_date', models.DateField(default=datetime.datetime.now)),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HospitalManagementApp.publicservant')),
                ('total_deaths', models.IntegerField(blank=True, null=True)),
                ('total_patients', models.IntegerField(blank=True, null=True)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalManagementApp.disease')),
            ],
        ),
    ]
